# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2

project_name: rago

release:
  github:
    owner: whoAngeel
    name: rago

builds:
  - main: ./cmd/rag/main.go
    binary: rago
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]

checksum:
  algorithm: sha256

changelog:
  filters:
    exclude:
      - "^docs:"
      - "^chore:"
